services:
  db:
    image: postgres:16-alpine
    container_name: rrhh_db
    environment:
      POSTGRES_USER: rrhh_owner
      POSTGRES_PASSWORD: dev_owner_pwd
      POSTGRES_DB: rrhh
      TZ: Europe/Madrid
      PGTZ: Europe/Madrid
    ports:
      - "5433:5432"
    volumes:
      - rrhh_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rrhh_owner -d rrhh"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  rrhh_pgdata:
